In [15]:
import os
os.path.join('f:','client_side')

'f:client_side'

In [41]:
os.listdir()

['.ipynb_checkpoints',
 'supermarkets-commas-no-header.txt',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Untitled.ipynb']

In [1]:
import pandas

In [3]:
# for help
pandas.read_csv?

In [2]:
df1 = pandas.read_csv("supermarkets.csv")
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [5]:
df2 = pandas.read_json('supermarkets.json')
df2

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [6]:
df3 = pandas.read_excel("supermarkets.xlsx",sheet_name=0)
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [96]:
df4 = pandas.read_csv("supermarkets-commas.txt")
# csv (chracter separated values) 
# if the file separated with comma (,) 
# you don't have to mentiond the separte value
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [16]:
df5 = pandas.read_csv("supermarkets-semi-colons.txt",sep=";")
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [75]:
# if you don't a have header line in your file
df6 = pandas.read_csv("supermarkets-commas-no-header.txt", header=None)
df6

0                1              2                 3    4            5   6
0  1     3666 21st St  San Francisco          CA 94114  USA      Madeira   8
1  2   735 Dolores St  San Francisco          CA 94119  USA  Bready Shop  15
2  3      332 Hill St  San Francisco  California 94114  USA  Super River  25
3  4     3995 23rd St  San Francisco          CA 94114  USA   Ben's Shop  10
4  5  1056 Sanchez St  San Francisco        California  USA      Sanchez  12
5  6  551 Alvarado St  San Francisco          CA 94114  USA   Richvalley  20

In [76]:
#To add Colums Names
df6.columns  = ["ID","Address","City","ZIP","Country","Name","Employees"]
df6

ID          Address           City               ZIP Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [77]:
# To set index for your table  by it's id's
# but id's as column is droped 
# inplace bool, default False >>> 
# >>> Modify the DataFrame in place (do not create a new object).
# if you don't sure of what are you doing and you want just test 
# store df6.set_index("ID",inplace=False) in another var and test what you need
# dfTest = df6.set_index("ID",inplace=False)
df6.set_index("ID",inplace=False,drop=False )

ID          Address           City               ZIP Country         Name  \
ID                                                                              
1    1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3    3      332 Hill St  San Francisco  California 94114     USA  Super River   
4    4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5    5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
6    6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [80]:
df7 = df6.set_index("Address",inplace=False,drop=True )
df7

ID           City               ZIP Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [142]:
df7.iloc[3 ,1:4]

City       San Francisco
ZIP             CA 94114
Country              USA
Name: 3995 23rd St, dtype: object

In [144]:
df7.shape # (rows , columns)

(6, 7)

In [167]:
df7['Continent'] = df7.shape[0] * ['North America']
df7

ID           City               ZIP Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees      Continent  
Address                                    
3666 21st St             8  North America  
735 Dolores St          15  North America  
332 Hill St             25  North America  
3995 23rd St            10  North America  
1056 Sanchez St         12  North America  
551 Alvarado St         20  North America

In [176]:
# update the whole column 
# with value form the table
df7['Continent'] = df7 ['Country'] + ', '+ 'North America'
df7

ID           City               ZIP Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees           Continent  
Address                                         
3666 21st St             8  USA, North America  
735 Dolores St          15  USA, North America  
332 Hill St             25  USA, North America  
3995 23rd St            10  USA, North America  
1056 Sanchez St         12  USA, North America  
551 Alvarado St         20  USA, North America

In [189]:
df7_t = df7.T
df7_t['Ahmed'] = df7_t.shape[0] * ['Awesome']
#df7_t
df7_tt = df7_t.T
#df7_tt = df7_tt.drop('Ahmed',0)
df7_tt


ID           City               ZIP Country         Name  \
Address                                                                    
3666 21st St     1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St   2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St      3  San Francisco  California 94114     USA  Super River   
3995 23rd St     4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St  5  San Francisco        California     USA      Sanchez   
551 Alvarado St  6  San Francisco          CA 94114     USA   Richvalley   

                Employees           Continent  
Address                                        
3666 21st St            8  USA, North America  
735 Dolores St         15  USA, North America  
332 Hill St            25  USA, North America  
3995 23rd St           10  USA, North America  
1056 Sanchez St        12  USA, North America  
551 Alvarado St        20  USA, North America

In [27]:
import geopy
import pandas
from geopy.geocoders import ArcGIS
nom = ArcGIS()
location = nom.geocode('3995 23rd St, San Francisco, CA 94114')
print(location.latitude)
#help(geopy.location.Location)

37.75292200397371


In [28]:
df = pandas.read_csv("supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [220]:
df["Address"] = df["Address"] + ', ' + df['City'] + ', ' + df['State'] + ', ' + df['Country']
df

ID                                            Address           City  \
0   1  3666 21st St, San Francisco, CA 94114, USA, Sa...  San Francisco   
1   2  735 Dolores St, San Francisco, CA 94119, USA, ...  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, ...  San Francisco   
3   4  3995 23rd St, San Francisco, CA 94114, USA, Sa...  San Francisco   
4   5  1056 Sanchez St, San Francisco, California, US...  San Francisco   
5   6  551 Alvarado St, San Francisco, CA 94114, USA,...  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [31]:
from geopy.geocoders import ArcGIS
nom = ArcGIS()
# To Apply function on the whole column
df['Coordinates'] = df["Address"].apply(nom.geocode)
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                        Coordinates  
0          8  (Travessa da Santa 21, 4740-451, Santa, Espose...  
1         15  (Dolores, Eastern Samar, Eastern Visayas, (12....  
2         25  (Hill Street, Connaught, (53.88333000000006, -...  
3         10   (3995, (-38.59906999999998, 145.59603963000006))  
4         12  (Sánchez, (19.23073000000005, -69.612949999999...  
5         20  (Alvarados, Zacatecas, (23.382180000000062, -1...

In [134]:
df['Latitude'] = df['Coordinates'].apply(lambda x: x.latitude)
df['Longitude'] = df['Coordinates'].apply(lambda x: x.longitude)
df
# try this the see the type  >>>> type(df.loc[0,'Coordinates']) <<<<
# Coordinates column is a Location (geopy.location.Location) object (Whiel using DataFrame you store object in a column)
# What if x is None (x is the return value of Coordinates) 
# In this case you must check if the x is None 
# Then store None in the column if the x is None
# df['Latitude'] = df['Coordinates'].apply(lambda x: x.latitude if x != None else None)


ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees                                        Coordinates   Latitude  \
0          8  (Travessa da Santa 21, 4740-451, Santa, Espose...  41.609562   
1         15  (Dolores, Eastern Samar, Eastern Visayas, (12....  12.052700   
2         25  (Hill Street, Connaught, (53.88333000000006, -...  53.883330   
3         10   (3995, (-38.59906999999998, 145.59603963000006)) -38.599070   
4         12  (Sánchez, (19.23073000000005, -69.612949999999...  19.230730   
5         20  (Alvarados, Zacatecas, (23.382180000000062, -1...  23.382180   

    Longitude  
0   -8.736951  
1  125.492230  
2   -8.083330  
3  145.596040  
4  -69.612950  
5 -102.396070

In [ ]:
# Starting with numpy

In [65]:
type([[123,12,123,12,33],[],[]])

list

In [69]:
import numpy
n = numpy.arange(27)
#n # This one diemension Array.
n = n.reshape(3,9) # This Two diemension Array like an image
n
#n = n.reshape(3,3,3) # This Three diemension Array like an image
#n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [68]:
m = numpy.asarray([[123,12,123,12,33],[],[]])
print(m)
type(m)

[list([123, 12, 123, 12, 33]) list([]) list([])]


numpy.ndarray

In [71]:
import cv2 

In [92]:
# 0 read image in grey mood
# 1 read image in BGR (Blue,Green,Red)
image_bgr = cv2.imread('smallgray.png',1)
image_bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [93]:
image_gray = cv2.imread('smallgray.png',0)
image_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [94]:
cv2.imwrite("test_small_img.png",image_gray)

True

In [104]:
#image_gray.shape #>>> (3,5)
image_gray[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [129]:
for i in image_gray: 
    print (i)
# i iterates on rows

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [131]:
for i in image_gray.T: 
    print (i)
# i iterates on Columns

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [132]:
for i in image_gray.flat: 
    print (i)
# i iterates on values

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [143]:
image_gray

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [144]:
ims =  numpy.hstack((image_gray,image_gray))

cv2.imwrite("test_small_img.png",ims)

True

In [150]:
imSplit = numpy.hsplit(ims,5)
print(imSplit)

[array([[187, 158],
       [198, 125],
       [209, 134]], dtype=uint8), array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8), array([[143, 187],
       [147, 198],
       [182, 209]], dtype=uint8), array([[158, 104],
       [125, 255],
       [134, 255]], dtype=uint8), array([[121, 143],
       [255, 147],
       [ 97, 182]], dtype=uint8)]
